// AUTO-GENERATED from /tmp/zombiegame2_spec/gen.js — do not edit by hand.
// Re-run `node gen.js | emit_rust.js` to regenerate after spec changes.

use crate::map_data::{Building, BuildingType, Prop, PropKind, RoofStyle, Segment, Theme};
use bevy::math::IVec2;

pub const SEGMENTS: [Segment; 5] = [
    Segment {
        id: 1,
        name: "Suburbs",
        pl_name: "Przedmieścia",
        difficulty: 1,
        theme: Theme::Suburb,
    },
    Segment {
        id: 2,
        name: "Downtown",
        pl_name: "Centrum miasta",
        difficulty: 2,
        theme: Theme::Downtown,
    },
    Segment {
        id: 3,
        name: "Industrial",
        pl_name: "Dzielnica przemysłowa",
        difficulty: 3,
        theme: Theme::Industrial,
    },
    Segment {
        id: 4,
        name: "Hospital & Park",
        pl_name: "Szpital i Park",
        difficulty: 4,
        theme: Theme::Hospital,
    },
    Segment {
        id: 5,
        name: "Military Checkpoint",
        pl_name: "Wojskowy checkpoint",
        difficulty: 5,
        theme: Theme::Military,
    },
];

pub const BUILDINGS: &[Building] = &[
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 1, y: 2, w: 7, h: 6, door: IVec2::new(1, 5) },
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 11, y: 1, w: 8, h: 7, door: IVec2::new(15, 1) },
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 1, y: 12, w: 8, h: 6, door: IVec2::new(1, 15) },
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 11, y: 12, w: 7, h: 6, door: IVec2::new(11, 15) },
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 28, y: 2, w: 6, h: 6, door: IVec2::new(31, 2) },
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 39, y: 2, w: 7, h: 6, door: IVec2::new(45, 5) },
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 38, y: 11, w: 8, h: 7, door: IVec2::new(45, 14) },
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 1, y: 28, w: 8, h: 6, door: IVec2::new(1, 31) },
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 11, y: 27, w: 7, h: 8, door: IVec2::new(11, 31) },
    Building { seg_id: 1, kind: BuildingType::Garage, roof: RoofStyle::Flat, x: 3, y: 40, w: 4, h: 4, door: IVec2::new(5, 43) },
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 11, y: 40, w: 8, h: 5, door: IVec2::new(15, 44) },
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 27, y: 28, w: 8, h: 6, door: IVec2::new(34, 31) },
    Building { seg_id: 1, kind: BuildingType::Garage, roof: RoofStyle::Flat, x: 40, y: 29, w: 4, h: 4, door: IVec2::new(43, 31) },
    Building { seg_id: 1, kind: BuildingType::House, roof: RoofStyle::Gable, x: 28, y: 40, w: 6, h: 5, door: IVec2::new(31, 44) },
    Building { seg_id: 1, kind: BuildingType::Shop, roof: RoofStyle::Flat, x: 40, y: 39, w: 5, h: 7, door: IVec2::new(42, 45) },
    Building { seg_id: 2, kind: BuildingType::Tower, roof: RoofStyle::Flat, x: 1, y: 1, w: 7, h: 7, door: IVec2::new(4, 1) },
    Building { seg_id: 2, kind: BuildingType::Apartment, roof: RoofStyle::Apt, x: 11, y: 1, w: 8, h: 8, door: IVec2::new(15, 1) },
    Building { seg_id: 2, kind: BuildingType::Church, roof: RoofStyle::Gable, x: 1, y: 11, w: 8, h: 8, door: IVec2::new(1, 15) },
    Building { seg_id: 2, kind: BuildingType::Shop, roof: RoofStyle::Flat, x: 12, y: 12, w: 5, h: 6, door: IVec2::new(14, 12) },
    Building { seg_id: 2, kind: BuildingType::Shop, roof: RoofStyle::Flat, x: 28, y: 2, w: 7, h: 6, door: IVec2::new(31, 2) },
    Building { seg_id: 2, kind: BuildingType::Shop, roof: RoofStyle::Flat, x: 39, y: 2, w: 6, h: 5, door: IVec2::new(42, 2) },
    Building { seg_id: 2, kind: BuildingType::Apartment, roof: RoofStyle::Apt, x: 1, y: 27, w: 8, h: 9, door: IVec2::new(1, 31) },
    Building { seg_id: 2, kind: BuildingType::Shop, roof: RoofStyle::Flat, x: 11, y: 28, w: 7, h: 6, door: IVec2::new(11, 31) },
    Building { seg_id: 2, kind: BuildingType::Shop, roof: RoofStyle::Flat, x: 2, y: 38, w: 6, h: 8, door: IVec2::new(5, 45) },
    Building { seg_id: 2, kind: BuildingType::Apartment, roof: RoofStyle::Apt, x: 27, y: 27, w: 9, h: 9, door: IVec2::new(31, 35) },
    Building { seg_id: 2, kind: BuildingType::Tower, roof: RoofStyle::Flat, x: 28, y: 38, w: 7, h: 8, door: IVec2::new(31, 45) },
    Building { seg_id: 2, kind: BuildingType::Bank, roof: RoofStyle::Flat, x: 39, y: 38, w: 7, h: 9, door: IVec2::new(42, 46) },
    Building { seg_id: 2, kind: BuildingType::Gas, roof: RoofStyle::Flat, x: 27, y: 12, w: 10, h: 5, door: IVec2::new(27, 16) },
    Building { seg_id: 3, kind: BuildingType::Tank, roof: RoofStyle::Round, x: 2, y: 12, w: 6, h: 5, door: IVec2::new(2, 14) },
    Building { seg_id: 3, kind: BuildingType::Depot, roof: RoofStyle::Flat, x: 11, y: 11, w: 8, h: 8, door: IVec2::new(15, 11) },
    Building { seg_id: 3, kind: BuildingType::Warehouse, roof: RoofStyle::Flat, x: 27, y: 1, w: 9, h: 8, door: IVec2::new(31, 1) },
    Building { seg_id: 3, kind: BuildingType::Warehouse, roof: RoofStyle::Flat, x: 38, y: 1, w: 9, h: 8, door: IVec2::new(46, 5) },
    Building { seg_id: 3, kind: BuildingType::Tank, roof: RoofStyle::Round, x: 29, y: 12, w: 5, h: 5, door: IVec2::new(31, 12) },
    Building { seg_id: 3, kind: BuildingType::Factory, roof: RoofStyle::Saw, x: 38, y: 11, w: 9, h: 8, door: IVec2::new(46, 15) },
    Building { seg_id: 3, kind: BuildingType::Shed, roof: RoofStyle::Flat, x: 3, y: 29, w: 4, h: 4, door: IVec2::new(3, 31) },
    Building { seg_id: 3, kind: BuildingType::Tank, roof: RoofStyle::Round, x: 12, y: 29, w: 6, h: 5, door: IVec2::new(12, 31) },
    Building { seg_id: 3, kind: BuildingType::Tank, roof: RoofStyle::Round, x: 2, y: 40, w: 5, h: 5, door: IVec2::new(4, 44) },
    Building { seg_id: 3, kind: BuildingType::Shed, roof: RoofStyle::Flat, x: 13, y: 40, w: 4, h: 5, door: IVec2::new(15, 44) },
    Building { seg_id: 3, kind: BuildingType::Shed, roof: RoofStyle::Flat, x: 40, y: 29, w: 4, h: 5, door: IVec2::new(43, 31) },
    Building { seg_id: 3, kind: BuildingType::Depot, roof: RoofStyle::Flat, x: 27, y: 38, w: 9, h: 9, door: IVec2::new(31, 46) },
    Building { seg_id: 3, kind: BuildingType::Tank, roof: RoofStyle::Round, x: 40, y: 39, w: 5, h: 6, door: IVec2::new(42, 44) },
    Building { seg_id: 4, kind: BuildingType::Park, roof: RoofStyle::Gable, x: 1, y: 2, w: 7, h: 6, door: IVec2::new(1, 5) },
    Building { seg_id: 4, kind: BuildingType::Park, roof: RoofStyle::Gable, x: 12, y: 2, w: 5, h: 6, door: IVec2::new(14, 2) },
    Building { seg_id: 4, kind: BuildingType::Garage, roof: RoofStyle::Flat, x: 1, y: 11, w: 8, h: 7, door: IVec2::new(1, 14) },
    Building { seg_id: 4, kind: BuildingType::Hospital, roof: RoofStyle::Flat, x: 38, y: 11, w: 9, h: 8, door: IVec2::new(46, 15) },
    Building { seg_id: 4, kind: BuildingType::Park, roof: RoofStyle::Gable, x: 2, y: 28, w: 5, h: 6, door: IVec2::new(2, 31) },
    Building { seg_id: 4, kind: BuildingType::Morgue, roof: RoofStyle::Flat, x: 11, y: 28, w: 7, h: 7, door: IVec2::new(11, 31) },
    Building { seg_id: 4, kind: BuildingType::Hospital, roof: RoofStyle::Flat, x: 1, y: 38, w: 8, h: 9, door: IVec2::new(5, 46) },
    Building { seg_id: 4, kind: BuildingType::Shed, roof: RoofStyle::Flat, x: 13, y: 40, w: 4, h: 4, door: IVec2::new(15, 43) },
    Building { seg_id: 4, kind: BuildingType::Hospital, roof: RoofStyle::Flat, x: 27, y: 27, w: 9, h: 9, door: IVec2::new(31, 35) },
    Building { seg_id: 4, kind: BuildingType::Park, roof: RoofStyle::Gable, x: 39, y: 29, w: 7, h: 4, door: IVec2::new(45, 31) },
    Building { seg_id: 4, kind: BuildingType::Park, roof: RoofStyle::Gable, x: 39, y: 39, w: 7, h: 6, door: IVec2::new(45, 42) },
    Building { seg_id: 5, kind: BuildingType::Tent, roof: RoofStyle::Tent, x: 2, y: 2, w: 5, h: 6, door: IVec2::new(4, 2) },
    Building { seg_id: 5, kind: BuildingType::Helipad, roof: RoofStyle::Pad, x: 11, y: 1, w: 8, h: 8, door: IVec2::new(15, 1) },
    Building { seg_id: 5, kind: BuildingType::Tent, roof: RoofStyle::Tent, x: 2, y: 12, w: 6, h: 5, door: IVec2::new(2, 14) },
    Building { seg_id: 5, kind: BuildingType::Tower, roof: RoofStyle::Flat, x: 13, y: 12, w: 4, h: 5, door: IVec2::new(15, 12) },
    Building { seg_id: 5, kind: BuildingType::Bunker, roof: RoofStyle::Flat, x: 27, y: 1, w: 9, h: 8, door: IVec2::new(31, 1) },
    Building { seg_id: 5, kind: BuildingType::Bunker, roof: RoofStyle::Flat, x: 38, y: 1, w: 9, h: 8, door: IVec2::new(46, 5) },
    Building { seg_id: 5, kind: BuildingType::Tent, roof: RoofStyle::Tent, x: 28, y: 12, w: 6, h: 6, door: IVec2::new(31, 12) },
    Building { seg_id: 5, kind: BuildingType::Tent, roof: RoofStyle::Tent, x: 39, y: 12, w: 7, h: 6, door: IVec2::new(45, 15) },
    Building { seg_id: 5, kind: BuildingType::Bunker, roof: RoofStyle::Flat, x: 1, y: 27, w: 8, h: 9, door: IVec2::new(1, 31) },
    Building { seg_id: 5, kind: BuildingType::Tent, roof: RoofStyle::Tent, x: 12, y: 28, w: 5, h: 6, door: IVec2::new(12, 31) },
    Building { seg_id: 5, kind: BuildingType::Tower, roof: RoofStyle::Flat, x: 2, y: 40, w: 5, h: 4, door: IVec2::new(2, 42) },
    Building { seg_id: 5, kind: BuildingType::Shed, roof: RoofStyle::Flat, x: 30, y: 29, w: 3, h: 4, door: IVec2::new(31, 32) },
    Building { seg_id: 5, kind: BuildingType::Shed, roof: RoofStyle::Flat, x: 41, y: 30, w: 3, h: 3, door: IVec2::new(43, 31) },
    Building { seg_id: 5, kind: BuildingType::Tent, roof: RoofStyle::Tent, x: 28, y: 39, w: 6, h: 6, door: IVec2::new(31, 44) },
    Building { seg_id: 5, kind: BuildingType::Helipad, roof: RoofStyle::Pad, x: 38, y: 38, w: 9, h: 9, door: IVec2::new(42, 46) },
];

pub const PROPS: &[Prop] = &[
    Prop { seg_id: 1, kind: PropKind::Tree, x: 13, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 27, y: 16, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 46, y: 46, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 34, y: 35, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 4, y: 35, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 14, y: 46, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 27, y: 46, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 2, y: 9, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 20, y: 31, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 34, y: 10, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 30, y: 11, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 33, y: 17, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 19, y: 37, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 45, y: 27, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 20, y: 10, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 7, y: 35, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 36, y: 5, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 34, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 4, y: 38, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 4, y: 37, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 46, y: 30, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 20, y: 45, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 38, y: 19, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 35, y: 13, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 37, y: 29, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 37, y: 46, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 0, y: 41, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 1, y: 35, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 31, y: 17, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 43, y: 36, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 45, y: 35, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 20, y: 32, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 19, y: 33, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 29, y: 38, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 19, y: 14, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 10, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 27, y: 11, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 19, y: 16, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 43, y: 19, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 46, y: 37, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 35, y: 40, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 33, y: 18, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 16, y: 37, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 41, y: 0, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 18, y: 19, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 20, y: 17, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 28, y: 13, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 17, y: 38, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 35, y: 9, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 3, y: 19, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 43, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 31, y: 15, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 32, y: 14, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 27, y: 9, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 20, y: 2, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Tree, x: 10, y: 10, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 8, y: 43, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 33, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 31, y: 0, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 13, y: 37, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 32, y: 9, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 42, y: 0, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 31, y: 10, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 40, y: 27, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 19, y: 38, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 35, y: 12, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 35, y: 36, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 20, y: 16, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 30, y: 0, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 3, y: 46, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 0, y: 9, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 37, y: 33, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 45, y: 32, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 29, y: 12, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 20, y: 6, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 12, y: 10, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 27, y: 37, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 35, y: 11, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 38, y: 41, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 38, y: 37, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 45, y: 30, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 35, y: 0, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 38, y: 42, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 3, y: 9, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 30, y: 14, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 37, y: 41, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 2, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 10, y: 19, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 31, y: 36, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 8, y: 0, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 46, y: 45, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 1, y: 0, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 38, y: 32, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 29, y: 35, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 38, y: 30, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 7, y: 36, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 17, y: 9, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Bush, x: 2, y: 0, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::HedgeH, x: 33, y: 46, w: 3, h: 1 },
    Prop { seg_id: 1, kind: PropKind::HedgeH, x: 40, y: 36, w: 3, h: 1 },
    Prop { seg_id: 1, kind: PropKind::HedgeH, x: 36, y: 39, w: 3, h: 1 },
    Prop { seg_id: 1, kind: PropKind::HedgeH, x: 16, y: 36, w: 3, h: 1 },
    Prop { seg_id: 1, kind: PropKind::HedgeH, x: 36, y: 44, w: 3, h: 1 },
    Prop { seg_id: 1, kind: PropKind::HedgeH, x: 3, y: 10, w: 3, h: 1 },
    Prop { seg_id: 1, kind: PropKind::HedgeH, x: 37, y: 35, w: 3, h: 1 },
    Prop { seg_id: 1, kind: PropKind::HedgeH, x: 35, y: 45, w: 3, h: 1 },
    Prop { seg_id: 1, kind: PropKind::HedgeH, x: 6, y: 9, w: 3, h: 1 },
    Prop { seg_id: 1, kind: PropKind::HedgeH, x: 32, y: 15, w: 3, h: 1 },
    Prop { seg_id: 1, kind: PropKind::HedgeV, x: 36, y: 31, w: 1, h: 3 },
    Prop { seg_id: 1, kind: PropKind::HedgeV, x: 0, y: 35, w: 1, h: 3 },
    Prop { seg_id: 1, kind: PropKind::HedgeV, x: 9, y: 43, w: 1, h: 3 },
    Prop { seg_id: 1, kind: PropKind::HedgeV, x: 35, y: 17, w: 1, h: 3 },
    Prop { seg_id: 1, kind: PropKind::HedgeV, x: 32, y: 36, w: 1, h: 3 },
    Prop { seg_id: 1, kind: PropKind::HedgeV, x: 37, y: 0, w: 1, h: 3 },
    Prop { seg_id: 1, kind: PropKind::HedgeV, x: 28, y: 14, w: 1, h: 3 },
    Prop { seg_id: 1, kind: PropKind::HedgeV, x: 9, y: 1, w: 1, h: 3 },
    Prop { seg_id: 1, kind: PropKind::HedgeV, x: 46, y: 38, w: 1, h: 3 },
    Prop { seg_id: 1, kind: PropKind::HedgeV, x: 36, y: 12, w: 1, h: 3 },
    Prop { seg_id: 1, kind: PropKind::Mailbox, x: 45, y: 29, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Mailbox, x: 6, y: 46, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Mailbox, x: 11, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Mailbox, x: 46, y: 9, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Mailbox, x: 19, y: 28, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Mailbox, x: 9, y: 37, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Mailbox, x: 36, y: 42, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Mailbox, x: 37, y: 43, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Trash, x: 20, y: 30, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Trash, x: 12, y: 36, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Trash, x: 30, y: 10, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Trash, x: 35, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Trash, x: 37, y: 28, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Trash, x: 19, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Blood, x: 20, y: 0, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Blood, x: 19, y: 18, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Blood, x: 34, y: 18, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Blood, x: 39, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Blood, x: 9, y: 40, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Blood, x: 37, y: 5, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Blood, x: 32, y: 46, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Blood, x: 14, y: 10, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Blood, x: 7, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Blood, x: 11, y: 46, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Lamp, x: 5, y: 19, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Lamp, x: 33, y: 12, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Lamp, x: 37, y: 38, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Lamp, x: 31, y: 14, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Lamp, x: 46, y: 27, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Lamp, x: 1, y: 19, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Lamp, x: 3, y: 0, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Lamp, x: 28, y: 20, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Lamp, x: 38, y: 36, w: 1, h: 1 },
    Prop { seg_id: 1, kind: PropKind::Lamp, x: 29, y: 46, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 1, y: 20, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 41, y: 17, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 45, y: 17, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 9, y: 43, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 28, y: 20, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 41, y: 13, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 42, y: 11, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 20, y: 5, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 20, y: 46, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 17, y: 19, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 3, y: 9, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 45, y: 13, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 37, y: 7, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 44, y: 16, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 19, y: 44, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 46, y: 12, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 43, y: 14, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 38, y: 33, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 16, y: 37, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 40, y: 34, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 20, y: 34, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Tree, x: 9, y: 2, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 46, y: 18, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 16, y: 42, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 42, y: 36, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 36, y: 6, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 0, y: 45, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 44, y: 8, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 14, y: 46, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 42, y: 29, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 40, y: 16, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 16, y: 39, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 41, y: 34, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bush, x: 10, y: 45, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Planter, x: 20, y: 19, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Planter, x: 38, y: 35, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Planter, x: 19, y: 20, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Planter, x: 30, y: 18, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Planter, x: 46, y: 15, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Planter, x: 18, y: 41, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Planter, x: 31, y: 20, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Planter, x: 19, y: 14, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Planter, x: 37, y: 1, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Planter, x: 20, y: 27, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bus, x: 34, y: 23, w: 3, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 19, y: 38, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 38, y: 30, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 20, y: 31, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 10, y: 12, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 17, y: 35, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 44, y: 30, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 40, y: 35, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 38, y: 15, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 27, y: 10, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 15, y: 42, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 44, y: 28, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Dumpster, x: 39, y: 28, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 36, y: 37, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 46, y: 9, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 44, y: 13, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 17, y: 10, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 19, y: 13, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 14, y: 19, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 9, y: 3, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 45, y: 34, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 35, y: 9, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 45, y: 12, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 9, y: 1, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 43, y: 9, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 15, y: 10, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 42, y: 8, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 19, y: 39, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 45, y: 32, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 44, y: 18, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Lamp, x: 41, y: 35, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bench, x: 43, y: 29, w: 2, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bench, x: 11, y: 44, w: 2, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bench, x: 17, y: 40, w: 2, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bench, x: 39, y: 14, w: 2, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bench, x: 39, y: 10, w: 2, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bench, x: 44, y: 36, w: 2, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bench, x: 36, y: 0, w: 2, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Bench, x: 12, y: 43, w: 2, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 10, y: 46, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 10, y: 14, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 16, y: 10, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 42, y: 0, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 0, y: 42, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 13, y: 37, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 40, y: 27, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 27, y: 9, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 18, y: 17, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 9, y: 46, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 44, y: 34, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 18, y: 16, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 15, y: 44, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Trash, x: 43, y: 16, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 16, y: 44, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 16, y: 19, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 1, y: 9, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 36, y: 7, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 37, y: 28, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 11, y: 46, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 20, y: 14, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 19, y: 27, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 18, y: 15, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 38, y: 13, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 37, y: 39, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 38, y: 28, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 45, y: 9, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 10, y: 38, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 36, y: 5, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Debris, x: 38, y: 36, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 33, y: 19, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 35, y: 20, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 20, y: 35, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 10, y: 36, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 19, y: 43, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 13, y: 10, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 40, y: 0, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 44, y: 14, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 15, y: 38, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 42, y: 34, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 46, y: 34, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 12, y: 36, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 13, y: 35, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 46, y: 29, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 0, y: 46, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Blood, x: 37, y: 38, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Sign, x: 38, y: 27, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Sign, x: 40, y: 9, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Sign, x: 46, y: 1, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Sign, x: 20, y: 11, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Sign, x: 15, y: 41, w: 1, h: 1 },
    Prop { seg_id: 2, kind: PropKind::Sign, x: 14, y: 39, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Tree, x: 37, y: 35, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Tree, x: 7, y: 1, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Tree, x: 8, y: 5, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Tree, x: 6, y: 2, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Tree, x: 46, y: 44, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Tree, x: 11, y: 20, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Tree, x: 7, y: 20, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Tree, x: 0, y: 0, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Bush, x: 30, y: 19, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Bush, x: 4, y: 7, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Bush, x: 40, y: 27, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Bush, x: 16, y: 20, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Bush, x: 1, y: 28, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Bush, x: 13, y: 4, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Truck, x: 3, y: 23, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Truck, x: 30, y: 24, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Truck, x: 23, y: 7, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Truck, x: 13, y: 24, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Truck, x: 28, y: 31, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Truck, x: 9, y: 42, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Truck, x: 31, y: 18, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 31, y: 30, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 13, y: 2, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 18, y: 45, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 16, y: 2, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 0, y: 19, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 4, y: 36, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 4, y: 34, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 8, y: 44, w: 3, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 19, y: 42, w: 2, h: 3 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 4, y: 0, w: 2, h: 3 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 31, y: 34, w: 2, h: 3 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 1, y: 35, w: 2, h: 3 },
    Prop { seg_id: 3, kind: PropKind::Container, x: 14, y: 7, w: 2, h: 3 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 35, y: 14, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 35, y: 31, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 37, y: 33, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 14, y: 6, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 0, y: 40, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 8, y: 39, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 18, y: 42, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 35, y: 13, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 9, y: 0, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 37, y: 38, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 35, y: 28, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 10, y: 36, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 37, y: 40, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 19, y: 7, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 37, y: 31, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 16, y: 36, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 12, y: 8, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 1, y: 38, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 10, y: 34, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 20, y: 6, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 13, y: 7, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Barrels, x: 7, y: 2, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 7, y: 4, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 2, y: 2, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 5, y: 3, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 5, y: 7, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 36, y: 28, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 11, y: 45, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 38, y: 33, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 12, y: 5, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 8, y: 43, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 0, y: 1, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 0, y: 3, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 11, y: 7, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 6, y: 3, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 6, y: 6, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 18, y: 20, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 45, y: 30, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 17, y: 8, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Pallet, x: 9, y: 9, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 19, y: 5, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 16, y: 0, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 35, y: 19, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 37, y: 37, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 30, y: 36, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 38, y: 28, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 36, y: 16, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 10, y: 38, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 14, y: 38, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 46, y: 29, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 18, y: 8, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 0, y: 17, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 11, y: 3, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 18, y: 40, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 16, y: 38, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 20, y: 16, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 36, y: 36, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 17, y: 6, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 3, y: 7, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 36, y: 27, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 18, y: 0, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 0, y: 44, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 27, y: 12, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 35, y: 11, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 12, y: 9, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Debris, x: 1, y: 32, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 37, y: 30, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 9, y: 37, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 34, y: 30, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 35, y: 16, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 6, y: 1, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 28, y: 33, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 2, y: 4, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 9, y: 2, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 19, y: 28, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 17, y: 4, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 3, y: 6, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Blood, x: 20, y: 37, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Oil, x: 10, y: 9, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Oil, x: 20, y: 31, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Oil, x: 30, y: 18, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Oil, x: 9, y: 19, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Oil, x: 41, y: 46, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Oil, x: 1, y: 8, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Oil, x: 12, y: 7, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Oil, x: 42, y: 37, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crane, x: 19, y: 40, w: 2, h: 2 },
    Prop { seg_id: 3, kind: PropKind::Forklift, x: 8, y: 38, w: 2, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Forklift, x: 41, y: 35, w: 2, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Forklift, x: 15, y: 35, w: 2, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 19, y: 27, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 3, y: 4, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 39, y: 35, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 13, y: 0, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 37, y: 32, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 28, y: 34, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 0, y: 32, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 40, y: 46, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 37, y: 45, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 0, y: 45, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 18, y: 1, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 9, y: 41, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 46, y: 30, w: 1, h: 1 },
    Prop { seg_id: 3, kind: PropKind::Crate, x: 45, y: 29, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 34, y: 8, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 11, y: 18, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 35, y: 42, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 4, y: 0, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 44, y: 9, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 40, y: 46, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 33, y: 14, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 29, y: 9, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 10, y: 9, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 44, y: 5, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 15, y: 12, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 33, y: 16, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 9, y: 32, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 37, y: 43, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 46, y: 34, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 9, y: 8, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 34, y: 41, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 32, y: 2, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 36, y: 5, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 34, y: 46, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 32, y: 44, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 6, y: 36, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 35, y: 46, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 36, y: 45, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 18, y: 18, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 10, y: 8, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 38, y: 2, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 37, y: 37, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 18, y: 37, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 28, y: 2, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 32, y: 43, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 40, y: 7, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 31, y: 45, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 28, y: 46, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 15, y: 38, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 15, y: 13, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 14, y: 11, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 10, y: 19, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 42, y: 0, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 30, y: 37, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 10, y: 16, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 9, y: 9, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 9, y: 6, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 4, y: 19, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 14, y: 45, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 46, y: 2, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 36, y: 10, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 17, y: 38, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 10, y: 40, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 18, y: 14, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 29, y: 16, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 11, y: 46, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 17, y: 12, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 20, y: 30, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 33, y: 20, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Tree, x: 20, y: 36, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 46, y: 3, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 7, y: 9, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 27, y: 45, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 19, y: 41, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 33, y: 5, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 33, y: 10, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 27, y: 16, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 12, y: 9, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 35, y: 19, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 44, y: 7, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 46, y: 1, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 10, y: 6, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 43, y: 6, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 34, y: 18, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 20, y: 32, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 36, y: 6, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 18, y: 4, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 3, y: 20, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 37, y: 35, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 19, y: 10, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 34, y: 37, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 12, y: 36, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 31, y: 0, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 29, y: 11, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 14, y: 10, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 28, y: 13, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 9, y: 20, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 34, y: 10, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 19, y: 3, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 20, y: 16, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 33, y: 17, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bush, x: 35, y: 8, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::HedgeH, x: 34, y: 16, w: 3, h: 1 },
    Prop { seg_id: 4, kind: PropKind::HedgeH, x: 28, y: 7, w: 3, h: 1 },
    Prop { seg_id: 4, kind: PropKind::HedgeH, x: 15, y: 9, w: 3, h: 1 },
    Prop { seg_id: 4, kind: PropKind::HedgeH, x: 44, y: 0, w: 3, h: 1 },
    Prop { seg_id: 4, kind: PropKind::HedgeH, x: 28, y: 42, w: 3, h: 1 },
    Prop { seg_id: 4, kind: PropKind::HedgeH, x: 33, y: 40, w: 3, h: 1 },
    Prop { seg_id: 4, kind: PropKind::HedgeH, x: 9, y: 36, w: 3, h: 1 },
    Prop { seg_id: 4, kind: PropKind::HedgeH, x: 12, y: 16, w: 3, h: 1 },
    Prop { seg_id: 4, kind: PropKind::HedgeV, x: 20, y: 0, w: 1, h: 3 },
    Prop { seg_id: 4, kind: PropKind::HedgeV, x: 29, y: 1, w: 1, h: 3 },
    Prop { seg_id: 4, kind: PropKind::HedgeV, x: 32, y: 8, w: 1, h: 3 },
    Prop { seg_id: 4, kind: PropKind::HedgeV, x: 31, y: 11, w: 1, h: 3 },
    Prop { seg_id: 4, kind: PropKind::HedgeV, x: 27, y: 17, w: 1, h: 3 },
    Prop { seg_id: 4, kind: PropKind::HedgeV, x: 37, y: 3, w: 1, h: 3 },
    Prop { seg_id: 4, kind: PropKind::HedgeV, x: 42, y: 2, w: 1, h: 3 },
    Prop { seg_id: 4, kind: PropKind::HedgeV, x: 18, y: 44, w: 1, h: 3 },
    Prop { seg_id: 4, kind: PropKind::Ambulance, x: 24, y: 12, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Ambulance, x: 22, y: 17, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Ambulance, x: 6, y: 24, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Ambulance, x: 0, y: 36, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Ambulance, x: 27, y: 4, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Gurney, x: 13, y: 18, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::Gurney, x: 15, y: 36, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::Gurney, x: 35, y: 3, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::Gurney, x: 34, y: 3, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::Gurney, x: 32, y: 16, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::Gurney, x: 32, y: 14, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::Gurney, x: 11, y: 41, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::Gurney, x: 41, y: 7, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::Bench, x: 8, y: 35, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bench, x: 15, y: 46, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bench, x: 32, y: 38, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bench, x: 41, y: 34, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bench, x: 15, y: 14, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bench, x: 34, y: 44, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Bench, x: 37, y: 36, w: 2, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Playground, x: 42, y: 8, w: 2, h: 2 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 19, y: 5, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 13, y: 15, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 19, y: 34, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 31, y: 16, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 20, y: 42, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 27, y: 6, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 45, y: 9, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 39, y: 1, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 1, y: 9, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 36, y: 13, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 27, y: 7, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 44, y: 6, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 32, y: 45, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 30, y: 39, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 13, y: 37, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 36, y: 37, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 40, y: 3, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Blood, x: 36, y: 2, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::BodyBag, x: 18, y: 0, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::BodyBag, x: 27, y: 8, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::BodyBag, x: 35, y: 12, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::BodyBag, x: 0, y: 31, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::BodyBag, x: 39, y: 36, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::BodyBag, x: 32, y: 5, w: 1, h: 2 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 40, y: 8, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 19, y: 30, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 5, y: 0, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 16, y: 10, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 12, y: 15, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 11, y: 19, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 18, y: 12, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 32, y: 37, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 30, y: 19, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 28, y: 16, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 39, y: 4, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Lamp, x: 14, y: 36, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Trash, x: 35, y: 17, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Trash, x: 27, y: 13, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Trash, x: 41, y: 36, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Trash, x: 28, y: 37, w: 1, h: 1 },
    Prop { seg_id: 4, kind: PropKind::Trash, x: 34, y: 42, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 11, y: 45, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 36, y: 16, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 17, y: 41, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 27, y: 46, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 20, y: 27, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 35, y: 16, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 0, y: 46, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 40, y: 34, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 20, y: 40, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 13, y: 41, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 35, y: 19, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 19, y: 13, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 19, y: 45, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 0, y: 15, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 34, y: 30, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Tree, x: 19, y: 38, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Bush, x: 3, y: 45, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Bush, x: 44, y: 10, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Bush, x: 35, y: 29, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Bush, x: 20, y: 12, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Bush, x: 35, y: 10, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Bush, x: 0, y: 44, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 14, y: 35, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 4, y: 38, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 0, y: 20, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 13, y: 36, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 5, y: 37, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 40, y: 28, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 9, y: 40, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 44, y: 28, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 43, y: 35, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 42, y: 27, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 16, y: 18, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagH, x: 12, y: 37, w: 3, h: 1 },
    Prop { seg_id: 5, kind: PropKind::SandbagV, x: 16, y: 42, w: 1, h: 3 },
    Prop { seg_id: 5, kind: PropKind::SandbagV, x: 13, y: 42, w: 1, h: 3 },
    Prop { seg_id: 5, kind: PropKind::SandbagV, x: 19, y: 31, w: 1, h: 3 },
    Prop { seg_id: 5, kind: PropKind::SandbagV, x: 10, y: 31, w: 1, h: 3 },
    Prop { seg_id: 5, kind: PropKind::SandbagV, x: 8, y: 40, w: 1, h: 3 },
    Prop { seg_id: 5, kind: PropKind::SandbagV, x: 39, y: 31, w: 1, h: 3 },
    Prop { seg_id: 5, kind: PropKind::SandbagV, x: 20, y: 6, w: 1, h: 3 },
    Prop { seg_id: 5, kind: PropKind::SandbagV, x: 8, y: 43, w: 1, h: 3 },
    Prop { seg_id: 5, kind: PropKind::MilTruck, x: 16, y: 22, w: 3, h: 2 },
    Prop { seg_id: 5, kind: PropKind::MilTruck, x: 7, y: 22, w: 3, h: 2 },
    Prop { seg_id: 5, kind: PropKind::MilTruck, x: 41, y: 24, w: 3, h: 2 },
    Prop { seg_id: 5, kind: PropKind::MilTruck, x: 23, y: 7, w: 3, h: 2 },
    Prop { seg_id: 5, kind: PropKind::MilTruck, x: 34, y: 34, w: 3, h: 2 },
    Prop { seg_id: 5, kind: PropKind::MilTruck, x: 7, y: 19, w: 3, h: 2 },
    Prop { seg_id: 5, kind: PropKind::Jeep, x: 26, y: 22, w: 2, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Jeep, x: 29, y: 22, w: 2, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Jeep, x: 28, y: 25, w: 2, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Jeep, x: 17, y: 25, w: 2, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Jeep, x: 14, y: 23, w: 2, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 19, y: 12, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 36, y: 31, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 10, y: 43, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 0, y: 38, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 18, y: 39, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 5, y: 19, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 30, y: 35, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 28, y: 35, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 0, y: 11, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 19, y: 35, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 19, y: 36, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 28, y: 27, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 16, y: 41, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 5, y: 20, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 4, y: 19, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 36, y: 43, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 18, y: 13, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 36, y: 36, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 35, y: 14, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 42, y: 19, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 28, y: 46, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 46, y: 35, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 0, y: 5, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crate, x: 20, y: 37, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 4, y: 9, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 41, y: 36, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 14, y: 18, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 9, y: 41, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 31, y: 27, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 36, y: 11, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 45, y: 30, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 18, y: 40, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 43, y: 34, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 35, y: 17, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 20, y: 16, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 34, y: 10, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 7, y: 45, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Barrels, x: 14, y: 20, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::RazorH, x: 14, y: 45, w: 4, h: 1 },
    Prop { seg_id: 5, kind: PropKind::RazorH, x: 8, y: 37, w: 4, h: 1 },
    Prop { seg_id: 5, kind: PropKind::RazorH, x: 39, y: 35, w: 4, h: 1 },
    Prop { seg_id: 5, kind: PropKind::RazorH, x: 9, y: 18, w: 4, h: 1 },
    Prop { seg_id: 5, kind: PropKind::RazorH, x: 42, y: 20, w: 4, h: 1 },
    Prop { seg_id: 5, kind: PropKind::RazorV, x: 20, y: 0, w: 1, h: 4 },
    Prop { seg_id: 5, kind: PropKind::RazorV, x: 8, y: 2, w: 1, h: 4 },
    Prop { seg_id: 5, kind: PropKind::RazorV, x: 39, y: 27, w: 1, h: 4 },
    Prop { seg_id: 5, kind: PropKind::RazorV, x: 12, y: 41, w: 1, h: 4 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 35, y: 41, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 28, y: 29, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 3, y: 46, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 4, y: 0, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 28, y: 10, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 3, y: 20, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 0, y: 9, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 20, y: 30, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 36, y: 17, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 36, y: 32, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 19, y: 39, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 37, y: 17, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 7, y: 10, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 9, y: 4, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 35, y: 43, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 29, y: 19, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 15, y: 18, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Blood, x: 39, y: 36, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 37, y: 35, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 20, y: 20, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 1, y: 10, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 5, y: 9, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 0, y: 39, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 34, y: 19, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 1, y: 46, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 35, y: 39, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 27, y: 28, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 31, y: 35, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 10, y: 10, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 28, y: 28, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 29, y: 20, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 9, y: 10, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 0, y: 45, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 38, y: 19, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 37, y: 30, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Debris, x: 40, y: 20, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crater, x: 18, y: 41, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crater, x: 12, y: 45, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crater, x: 6, y: 46, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crater, x: 9, y: 17, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Crater, x: 10, y: 20, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Flag, x: 9, y: 7, w: 1, h: 1 },
    Prop { seg_id: 5, kind: PropKind::Flag, x: 15, y: 37, w: 1, h: 1 },
];

pub const ZOMBIE_SPAWNS: &[(u8, IVec2)] = &[
    (1, IVec2::new(33, 9)),
    (1, IVec2::new(28, 38)),
    (1, IVec2::new(27, 0)),
    (1, IVec2::new(9, 36)),
    (1, IVec2::new(35, 43)),
    (2, IVec2::new(6, 9)),
    (2, IVec2::new(19, 31)),
    (2, IVec2::new(20, 6)),
    (2, IVec2::new(47, 15)),
    (2, IVec2::new(47, 36)),
    (2, IVec2::new(14, 41)),
    (2, IVec2::new(43, 20)),
    (3, IVec2::new(14, 47)),
    (3, IVec2::new(30, 27)),
    (3, IVec2::new(19, 34)),
    (3, IVec2::new(45, 36)),
    (3, IVec2::new(46, 37)),
    (3, IVec2::new(20, 30)),
    (3, IVec2::new(0, 28)),
    (3, IVec2::new(44, 36)),
    (3, IVec2::new(13, 38)),
    (4, IVec2::new(47, 4)),
    (4, IVec2::new(12, 13)),
    (4, IVec2::new(5, 35)),
    (4, IVec2::new(46, 37)),
    (4, IVec2::new(44, 27)),
    (4, IVec2::new(17, 37)),
    (4, IVec2::new(11, 17)),
    (4, IVec2::new(8, 32)),
    (4, IVec2::new(39, 47)),
    (4, IVec2::new(10, 7)),
    (4, IVec2::new(35, 1)),
    (5, IVec2::new(1, 18)),
    (5, IVec2::new(14, 42)),
    (5, IVec2::new(31, 47)),
    (5, IVec2::new(20, 10)),
    (5, IVec2::new(35, 12)),
    (5, IVec2::new(2, 10)),
    (5, IVec2::new(3, 47)),
    (5, IVec2::new(12, 20)),
    (5, IVec2::new(37, 27)),
    (5, IVec2::new(36, 20)),
    (5, IVec2::new(17, 39)),
    (5, IVec2::new(28, 37)),
    (5, IVec2::new(1, 0)),
];

